"""Simplifying down to one table with fewer fields

Revision ID: c0a86ea226b7
Revises: 3220b2f7ef30
Create Date: 2023-03-27 15:18:47.051791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a86ea226b7'
down_revision = '3220b2f7ef30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('users')
    op.add_column('questions', sa.Column('answer1', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('answer2', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('answer3', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('answer4', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.String(), nullable=True))
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'answer')
    op.drop_column('questions', 'difficulty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('difficulty', sa.VARCHAR(), nullable=True))
    op.add_column('questions', sa.Column('answer', sa.VARCHAR(), nullable=True))
    op.add_column('questions', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'answer4')
    op.drop_column('questions', 'answer3')
    op.drop_column('questions', 'answer2')
    op.drop_column('questions', 'answer1')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
